### PR TITLE
add space option

### PR DESCRIPTION
**Pull request by yields**
on space add a tag.

### CODE REVIEW

**Comment by yields** [comment]
ping @visionmedia

**Comment by tj** [comment]
sweet! thanks

**Comment by azhang** [comment]
`{ space: true }` to disable spaces seems unintuitive. Thoughts?

**Comment by yields** [comment]
hmm looks like `{ space: true }` [enables](https://github.com/component/pillbox/blob/b90222df4db04c0b8d04a680e6349c8c8391c7a5/index.js#L64) spaces ?

**Comment by azhang** [comment]
Sorry, "disable" is kind of ambiguous. I meant that `{ space: true }` will _disallow_ spaces inside tags, whereas `{ space: false }` will _allow_ spaces inside tags. It seems a little backwards but I'm not sure if that's just me.

**Comment by yields** [comment]
oh now i see what you mean haha, yeah poor naming by me (as always :P), i guess you can think of it as "create a tag if the user hits `space`" so `space=true`

haha poor naming sorry about that :P

**Comment by azhang** [comment]
I'll make a pull req to reverse it and add documentation as well. :)

**Comment by yields** [comment]
reversing it is bad IMHO, since it will break apps / components (because component doesn't use semver yet)

i think giving it another name with backwards support is better.

**Comment by azhang** [comment]
Gotcha, will do. thanks!

**Pull request merged**
